language: node_js
node:
  - 12
cache:
  npm: false

install:
  - npm ci

before_script:
  - npm install
  - npm install --save-dev jest


script: 
  - npm test
  - npm run test:coveralls
  - npm start